@echo off
rem colourMatik - uninstaller (Windows). Removes the panel, effect, autostart and engine.
echo ==^> Stopping the engine...
powershell -NoProfile -Command "Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -match 'colourmatik.webapp' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }" 2>nul
echo ==^> Removing autostart...
del "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\colourMatik Engine.lnk" 2>nul
echo ==^> Removing the Premiere panel...
rmdir /s /q "%APPDATA%\Adobe\UXP\Plugins\External\com.colourmatik.panel_1.0.0" 2>nul
powershell -NoProfile -Command "$r=Join-Path $env:APPDATA 'Adobe\UXP\PluginsInfo\v1\premierepro.json'; if(Test-Path $r){$j=Get-Content $r -Raw|ConvertFrom-Json; $j.plugins=@($j.plugins|Where-Object{$_.pluginId -ne 'com.colourmatik.panel'}); ($j|ConvertTo-Json -Depth 8 -Compress)|Set-Content -Encoding UTF8 $r}"
echo ==^> Removing the native effect (needs admin)...
powershell -NoProfile -Command "Start-Process cmd -Verb RunAs -ArgumentList '/c del \"C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\colourMatik.aex\"'"
echo ==^> Removing the support folder...
rmdir /s /q "%APPDATA%\colourMatik" 2>nul
echo Done. Restart Premiere Pro to finish. (The colourMatik app folder was left in place.)
pause
